# Here we can add some custom package installations

library(remotes)
remotes::install_github("repboxr/GithubActions", upgrade="never", force=TRUE)
remotes::install_github("repboxr/sourcemodify", upgrade="never", force=TRUE)
remotes::install_github("repboxr/pkgFunIndex", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxUtils", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxCodeText", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxRun", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxGithub", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxArt", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxR", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxHtml", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxDB", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxRfun", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxEvaluate", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxReg", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxMap", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxStata", upgrade="never", force=TRUE)
remotes::install_github("repboxr/ExtractSciTab", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxDeploy", upgrade="never", force=TRUE)
remotes::install_github("repboxr/repboxverse", upgrade="never", force=TRUE)

#pkgs = repboxDeploy:::repbox_packages()
#cat(paste0("remotes::install_github(\"repboxr/", pkgs, "\", upgrade=\"never\", force=TRUE)", collapse="\n"))
